from rest_framework import serializers
from .models import Summary

class SummaryRequestSerializer(serializers.ModelSerializer):
    class Meta:
        model = Summary
        fields = ['url']
        # We only want the URL from the user. 
        # ID, status, and output are generated by the system.

class SummaryDetailSerializer(serializers.ModelSerializer):
    class Meta:
        model = Summary
        fields = ['id', 'url', 'status', 'output_summary', 'created_at']